services:

  employee-search-api:
    build: .
    container_name: employee-search-api
    ports:
      - "8081:8081"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      SPRING_ELASTICSEARCH_URIS: http://elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.5
    container_name: employee-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  elasticsearch-data: