
pipeline {
    agent any

    tools {
        jdk 'JDK-21'
        maven 'Maven 3.9.16'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/vrushaliphaltane11-ctrl/employee-search-api'
            }
        }

        stage('Verify Java') {
            steps {
                bat 'java -version'
            }
        }

        stage('Verify Maven') {
            steps {
                bat 'mvn -version'
            }
        }

        stage('Compile') {
            steps {
                dir('employee-search-api') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Unit Test + JaCoCo') {
            steps {
                dir('employee-search-api') {
                    bat 'mvn test'
                }
            }
        }

       stage('SonarQube Analysis') {
    steps {
        dir('employee-search-api') {
            withSonarQubeEnv('SonarQube') {
                withCredentials([string(credentialsId: 'sonarqube-token', variable: 'SONAR_TOKEN')]) {
                    bat '''
                        mvn sonar:sonar ^
                        -Dsonar.projectKey=employee-search-api ^
                        -Dsonar.projectName="Employee Search API" ^
                        -Dsonar.token=%SONAR_TOKEN%
                    '''
                }
            }
        }
    }
}

        stage('Package') {
            steps {
                dir('employee-search-api') {
                    bat 'mvn package -DskipTests'
                }
            }
        }

        stage('Verify Jar') {
            steps {
                dir('employee-search-api') {
                    bat 'dir target\\*.jar'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('employee-search-api') {
                    bat 'docker build -t employee-search-api:latest .'
                }
            }
        }

        stage('Docker Deploy') {
            steps {

                // Stop old container if it is running
                bat 'docker stop employee-search-api-container 2>NUL || exit /B 0'

                // Remove old container
                bat 'docker rm employee-search-api-container 2>NUL || exit /B 0'

                // Start new container
                bat 'docker run -d --name employee-search-api-container -p 8082:8081 employee-search-api:latest'
            }
        }
    }

    post {
        always {
            junit 'employee-search-api/target/surefire-reports/*.xml'

            archiveArtifacts artifacts: 'employee-search-api/target/site/jacoco/**',
                             allowEmptyArchive: true
        }
    }
}
